name: Build, Push, and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push microservicio-video
        uses: docker/build-push-action@v2
        with:
          context: ./microservicio-video
          file: ./microservicio-video/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/microservicio-video:latest

      - name: Build and push online-coffee
        uses: docker/build-push-action@v2
        with:
          context: ./online-coffee
          file: ./online-coffee/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/online-coffee:latest

      - name: Build and push service-offers
        uses: docker/build-push-action@v2
        with:
          context: ./service-offers
          file: ./service-offers/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/service-offers:latest
      - name: Fix routes in docker-compose.yml
        run: |
          sed -i 's|build: \./|build: ../|g' ./docker/docker-compose.yml
          echo "Updated content from docker-compose.yml:"
          cat ./docker/docker-compose.yml

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  
          script: |
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/microservicio-video:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/online-coffee:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/service-offers:latest
            docker stop microservicio-video || true
            docker stop online-coffee || true
            docker stop service-offers || true
            docker rm microservicio-video || true
            docker rm online-coffee || true
            docker rm service-offers || true
            docker run -d --name microservicio-video -p 8080:3001 ${{ secrets.DOCKER_USERNAME }}/microservicio-video:latest
            docker run -d --name online-coffee -p 8001:3001 ${{ secrets.DOCKER_USERNAME }}/online-coffee:latest
            docker run -d --name service-offers -p 8002:3000 ${{ secrets.DOCKER_USERNAME }}/service-offers:latest